name: Bug Report
description: Report an issue with Galaxy Book Enabler
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue! Please fill out the sections below to help us diagnose the problem.
        
        **Before submitting:**
        - Check if a similar issue already exists
        - Make sure you're using the latest version of the script
  
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe what went wrong
      placeholder: "Example: Quick Share doesn't connect to my phone, shows 'Searching for devices...' forever"
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: What should have happened instead?
      placeholder: "Example: Expected Quick Share to detect my Galaxy S24 and allow file transfer"
    validations:
      required: true
  
  - type: dropdown
    id: feature
    attributes:
      label: Which feature is affected?
      multiple: true
      options:
        - Installation/Setup
        - Quick Share
        - Camera Share
        - Storage Share
        - Multi Control
        - Second Screen
        - Samsung Notes
        - Samsung Gallery
        - Samsung Cloud
        - AI Select
        - Samsung Account
        - System Support Engine (SSSE)
        - Other
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: Installation Log
      description: |
        **IMPORTANT:** Please attach your installation log file. This helps us diagnose issues quickly.
        
        The log is saved to: `%TEMP%\GalaxyBookEnabler_YYYYMMDD_HHMMSS.log`
        
        You can find it by:
        1. Press Win+R
        2. Type: `%TEMP%`
        3. Look for the newest `GalaxyBookEnabler_*.log` file
        4. Drag and drop it here or paste its contents
        
        **If you ran the script via `irm | iex`, the log should still be saved automatically.**
      placeholder: "Drag and drop your log file here, or paste its contents"
      render: shell
    validations:
      required: false
  
  - type: textarea
    id: hardware
    attributes:
      label: Hardware Information
      description: |
        This information is included in the log file. If you don't have the log, please provide:
        - Wi-Fi adapter model (from Device Manager)
        - Bluetooth adapter model (from Device Manager)
        - CPU model (Intel/AMD/Qualcomm)
        - Windows version (Settings → System → About)
      placeholder: |
        Wi-Fi: Intel Wi-Fi 6E AX211
        Bluetooth: Intel Bluetooth
        CPU: Intel Core i7-1360P
        Windows: 11 Pro 23H2 (Build 22631.4602)
    validations:
      required: false
  
  - type: input
    id: version
    attributes:
      label: Galaxy Book Enabler Version
      description: What version of the script are you using?
      placeholder: "3.1.0"
    validations:
      required: true
  
  - type: dropdown
    id: windows-version
    attributes:
      label: Windows Version
      options:
        - Windows 11 24H2
        - Windows 11 23H2
        - Windows 11 22H2
        - Windows 11 21H2
        - Windows 10 22H2
        - Windows 10 21H2
        - Other
    validations:
      required: true
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might help (screenshots, error messages, etc.)
      placeholder: Add any other context about the problem here
